- hosts: cnvlab
  remote_user: centos
  become: yes
  vars:
    package: docker
  tasks:
  - name: check if "{{ package }}" is installed
    shell: "rpm -qa | grep {{ package }}"
#    register: found
#  - name: report notdes where it s note
#    debug:
#       msg: "{{ inventory_hostname }}"
#    when:  (found.results|length != 1)
