---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  labels:
    kubevirt-vm: fedora-multus-2
  name: fedora-multus-2
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt-vm: fedora-multus-2
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk            
            volumeName: containervolume
          - disk:
              bus: virtio
            name: cloudinitdisk
            volumeName: cloudinitvolume
          interfaces:
          - bridge: {}
            name: default
          - bridge: {}
            macAddress: 20:37:cf:e0:ad:f2
            name: ovs-br1
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: ovs-br1
        name: ovs-br1
      volumes:
      - name: containervolume
        containerDisk:
          image: docker.io/kubevirt/fedora-cloud-registry-disk-demo:latest
      - cloudInitNoCloud:
          userData: |-
            #!/bin/bash
            echo fedora | passwd fedora --stdin
            ip address add 11.0.0.6/24 dev eth1
            ifconfig eth1 up
        name: cloudinitvolume
