apiVersion: v1
kind: Service
metadata:
  name: vm1-ssh
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/domain: vm1
  sessionAffinity: None
  type: NodePort
